name: Deploy Python project to Azure Function App

on:
    push

permissions:
        id-token: write
        contents: read
        
jobs: 
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: azure/login@v2
          with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}